### ISSUE TITLE
Crashes with Geckolibs Item Network code

### ISSUE THREAD

**Issue by AzureDoom** [TonimatasDEV/PacketSizeDoublerForge#4]
Loading this mod with any mod that uses Geckolibs Item Network code causes a crash. 

Tested with: 
- MCDoom-Forge-1.19.2-4.2.26
- curios-forge-1.19.2-5.1.1.0
- geckolib-forge-1.19-3.1.39
- PacketSizeDoublerForge-1.0.4-1.19.x

Crash Report: https://gist.github.com/AzureDoom/157847b3a7451bff95b319d8c8fe39ae

Assuming it's likely in your mixin here: https://github.com/TonimatasDEV/PacketSizeDoublerForge/blob/master/1.19.x/src/main/java/net/tonimatasdev/packetsizedoublerforge/mixin/CompressionEncoderMixin.java

**Comment by TonimatasDEV** [comment]
Fixed-1.0.5
[PacketSizeDoublerForge-1.0.5.zip](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/10333941/PacketSizeDoublerForge-1.0.5.zip)
