### ISSUE TITLE
Crash on Load Phase

### ISSUE THREAD

**Issue by ElardHuaraca** [TonimatasDEV/PacketSizeDoublerForge#5]
Crash on Load Phase because new version server forge is not suported

Minecraft : 1.19.3-44.1.22
Mod Version : PacketSizeDoublerForge-1.0.7-1.19.x

![imagen](https://user-images.githubusercontent.com/56555556/225187719-6c0f3f90-61e1-4543-b78a-52c08cdd2bac.png)

**Comment by TonimatasDEV** [comment]
> Crash on Load Phase because new version server forge is not suported
> 
> Minecraft : 1.19.3-44.1.22 Mod Version : PacketSizeDoublerForge-1.0.7-1.19.x
> 
> ![imagen](https://user-images.githubusercontent.com/56555556/225187719-6c0f3f90-61e1-4543-b78a-52c08cdd2bac.png)

Update you forge to 44.1.44

**Comment by IshimaKudzi** [comment]
I got this too

**Comment by ElardHuaraca** [comment]
@TonimatasDEV go to discord and dowload new version
