### ISSUE TITLE
Doesnt do anything on 1.19.2

### ISSUE THREAD

**Issue by Xplodin** [TonimatasDEV/PacketSizeDoublerForge#6]
I load up, and get the Payload may not be larger than 1048576 bytes
error on the client

Installed on both client and server

**Comment by TonimatasDEV** [comment]
> I load up, and get the Payload may not be larger than 1048576 bytes error on the client
> 
> Installed on both client and server

Sorry but, this packet is not implemented, test this alpha version:
[PacketSizeDoublerForge-1.0.8-1.19.x.zip](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/11053290/PacketSizeDoublerForge-1.0.8-1.19.x.zip)

**Comment by Xplodin** [comment]
found a fix for ya:
inside ClientboundCustomQueryPacketMixin.java
replace @Mixin(ServerboundCustomQueryPacket.class) with @Mixin(ClientboundCustomQueryPacket.class)


and import net.minecraft.network.protocol.login.ServerboundCustomQueryPacket;
with import net.minecraft.network.protocol.login.ClientboundCustomQueryPacket;


fixes mod startup and boots normally (even with immersive portals)

**Comment by TonimatasDEV** [comment]
> fixes mod startup and boots normally (even with immersive portals)
> 
> I think the issue was having Serverbound inside of the Clientbound
> 
> edit: sorry I mistook it booting up, still sadly causes payload may not be larger than ... error

I learning for fix this error, it is very rare

**Comment by TonimatasDEV** [comment]
Fixed in 1.0.8
