### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by YassaaaTU** [TonimatasDEV/PacketSizeDoublerForge#8]
MC Version: 1.19.2
Mod Version: [PacketSizeDoubler 1.0.8 V: 1.19.x](https://legacy.curseforge.com/minecraft/mc-mods/packet-size-doubler-forge/files/4552388)

---

[debug.log](https://mclo.gs/OC2nOUI)

I am using this [modpack](https://legacy.curseforge.com/minecraft/modpacks/chill-ecke/files/4567328)

I installed your mod. got server crash (i am using a server pack that excludes client side mods). disabled the mods pluto and xl packets. tried again. server crash on startup still occurs

**Comment by TonimatasDEV** [comment]
> MC Version: 1.19.2 Mod Version: [PacketSizeDoubler 1.0.8 V: 1.19.x](https://legacy.curseforge.com/minecraft/mc-mods/packet-size-doubler-forge/files/4552388)
> 
> [debug.log](https://mclo.gs/OC2nOUI)
> 
> I am using this [modpack](https://legacy.curseforge.com/minecraft/modpacks/chill-ecke/files/4567328)
> 
> I installed your mod. got server crash (i am using a server pack that excludes client side mods). disabled the mods pluto and xl packets. tried again. server crash on startup still occurs

Test with this developement version:

[PacketSizeDoubler-1.0.9-1.19.x.zip](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/11647334/PacketSizeDoubler-1.0.9-1.19.x.zip)

**Comment by YassaaaTU** [comment]
> > MC Version: 1.19.2 Mod Version: [PacketSizeDoubler 1.0.8 V: 1.19.x](https://legacy.curseforge.com/minecraft/mc-mods/packet-size-doubler-forge/files/4552388)
> > [debug.log](https://mclo.gs/OC2nOUI)
> > I am using this [modpack](https://legacy.curseforge.com/minecraft/modpacks/chill-ecke/files/4567328)
> > I installed your mod. got server crash (i am using a server pack that excludes client side mods). disabled the mods pluto and xl packets. tried again. server crash on startup still occurs
> 
> Test with this developement version:
> 
> [PacketSizeDoubler-1.0.9-1.19.x.zip](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/11647334/PacketSizeDoubler-1.0.9-1.19.x.zip)

Server seems to start. Was this mod needed on client and server side? If no then now it won't let me join if I only have it installed on the server. Haven't tried to join while its installed on both sides.

**Comment by TonimatasDEV** [comment]
> 



> > > MC Version: 1.19.2 Mod Version: [PacketSizeDoubler 1.0.8 V: 1.19.x](https://legacy.curseforge.com/minecraft/mc-mods/packet-size-doubler-forge/files/4552388)
> > > [debug.log](https://mclo.gs/OC2nOUI)
> > > I am using this [modpack](https://legacy.curseforge.com/minecraft/modpacks/chill-ecke/files/4567328)
> > > I installed your mod. got server crash (i am using a server pack that excludes client side mods). disabled the mods pluto and xl packets. tried again. server crash on startup still occurs
> > 
> > 
> > Test with this developement version:
> > [PacketSizeDoubler-1.0.9-1.19.x.zip](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/11647334/PacketSizeDoubler-1.0.9-1.19.x.zip)
> 
> Server seems to start. Was this mod needed on client and server side? If no then now it won't let me join if I only have it installed on the server. Haven't tried to join while its installed on both sides.

It is not necessary on either side, it may be that on one side you do not need it

**Comment by YassaaaTU** [comment]
> > 
> 
> > > > MC Version: 1.19.2 Mod Version: [PacketSizeDoubler 1.0.8 V: 1.19.x](https://legacy.curseforge.com/minecraft/mc-mods/packet-size-doubler-forge/files/4552388)
> > > > [debug.log](https://mclo.gs/OC2nOUI)
> > > > I am using this [modpack](https://legacy.curseforge.com/minecraft/modpacks/chill-ecke/files/4567328)
> > > > I installed your mod. got server crash (i am using a server pack that excludes client side mods). disabled the mods pluto and xl packets. tried again. server crash on startup still occurs
> > > 
> > > 
> > > Test with this developement version:
> > > [PacketSizeDoubler-1.0.9-1.19.x.zip](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/11647334/PacketSizeDoubler-1.0.9-1.19.x.zip)
> > 
> > 
> > Server seems to start. Was this mod needed on client and server side? If no then now it won't let me join if I only have it installed on the server. Haven't tried to join while its installed on both sides.
> 
> It is not necessary on either side, it may be that on one side you do not need it

It did not let me join the server with the mod only installed on the server

**Comment by TonimatasDEV** [comment]
> 

That's weird, did you manage to join?

**Comment by TonimatasDEV** [comment]
> > > 
> > 
> > 
> > > > > MC Version: 1.19.2 Mod Version: [PacketSizeDoubler 1.0.8 V: 1.19.x](https://legacy.curseforge.com/minecraft/mc-mods/packet-size-doubler-forge/files/4552388)
> > > > > [debug.log](https://mclo.gs/OC2nOUI)
> > > > > I am using this [modpack](https://legacy.curseforge.com/minecraft/modpacks/chill-ecke/files/4567328)
> > > > > I installed your mod. got server crash (i am using a server pack that excludes client side mods). disabled the mods pluto and xl packets. tried again. server crash on startup still occurs
> > > > 
> > > > 
> > > > Test with this developement version:
> > > > [PacketSizeDoubler-1.0.9-1.19.x.zip](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/11647334/PacketSizeDoubler-1.0.9-1.19.x.zip)
> > > 
> > > 
> > > Server seems to start. Was this mod needed on client and server side? If no then now it won't let me join if I only have it installed on the server. Haven't tried to join while its installed on both sides.
> > 
> > 
> > It is not necessary on either side, it may be that on one side you do not need it
> 
> It did not let me join the server with the mod only installed on the server

That's weird, did you manage to join?

**Comment by YassaaaTU** [comment]
> > > > 
> > > 
> > > 
> > > > > > MC Version: 1.19.2 Mod Version: [PacketSizeDoubler 1.0.8 V: 1.19.x](https://legacy.curseforge.com/minecraft/mc-mods/packet-size-doubler-forge/files/4552388)
> > > > > > [debug.log](https://mclo.gs/OC2nOUI)
> > > > > > I am using this [modpack](https://legacy.curseforge.com/minecraft/modpacks/chill-ecke/files/4567328)
> > > > > > I installed your mod. got server crash (i am using a server pack that excludes client side mods). disabled the mods pluto and xl packets. tried again. server crash on startup still occurs
> > > > > 
> > > > > 
> > > > > Test with this developement version:
> > > > > [PacketSizeDoubler-1.0.9-1.19.x.zip](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/11647334/PacketSizeDoubler-1.0.9-1.19.x.zip)
> > > > 
> > > > 
> > > > Server seems to start. Was this mod needed on client and server side? If no then now it won't let me join if I only have it installed on the server. Haven't tried to join while its installed on both sides.
> > > 
> > > 
> > > It is not necessary on either side, it may be that on one side you do not need it
> > 
> > 
> > It did not let me join the server with the mod only installed on the server
> 
> That's weird, did you manage to join?

I removed the mod for now so the other players can join and because I have to go to sleep because I have work tomorrow.

**Comment by TonimatasDEV** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > > > MC Version: 1.19.2 Mod Version: [PacketSizeDoubler 1.0.8 V: 1.19.x](https://legacy.curseforge.com/minecraft/mc-mods/packet-size-doubler-forge/files/4552388)
> > > > > > > [debug.log](https://mclo.gs/OC2nOUI)
> > > > > > > I am using this [modpack](https://legacy.curseforge.com/minecraft/modpacks/chill-ecke/files/4567328)
> > > > > > > I installed your mod. got server crash (i am using a server pack that excludes client side mods). disabled the mods pluto and xl packets. tried again. server crash on startup still occurs
> > > > > > 
> > > > > > 
> > > > > > Test with this developement version:
> > > > > > [PacketSizeDoubler-1.0.9-1.19.x.zip](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/11647334/PacketSizeDoubler-1.0.9-1.19.x.zip)
> > > > > 
> > > > > 
> > > > > Server seems to start. Was this mod needed on client and server side? If no then now it won't let me join if I only have it installed on the server. Haven't tried to join while its installed on both sides.
> > > > 
> > > > 
> > > > It is not necessary on either side, it may be that on one side you do not need it
> > > 
> > > 
> > > It did not let me join the server with the mod only installed on the server
> > 
> > 
> > That's weird, did you manage to join?
> 
> I removed the mod for now so the other players can join and because I have to go to sleep because I have work tomorrow.

Work the new version in both sides?

**Comment by TonimatasDEV** [comment]
Fixed
