### ISSUE TITLE
Feature request: A config to disable and enable each mixin

### ISSUE THREAD

**Issue by DraTrav** [TonimatasDEV/PacketSizeDoublerForge#9]
A config to disable each mixin/ Feature. Allowing this mod to be more compatible with other mods that do similar things such as Connectivity.

**Comment by TonimatasDEV** [comment]
> A config to disable each mixin/ Feature. Allowing this mod to be more compatible with other mods that do similar things such as Connectivity.

I fixed the compatibility with other mods, Connectivity doesn't disable the mixin, only put true or false in the packet limit
